services:
  storage:
    image: redis
    volumes:
      - ./service_counter/data:/data
  counter:
    image: 14101916/redis_counter:v1.0.0
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 3003:3003
    depends_on:
      - storage        
  books:
    build: ./service_books/
    environment:
      - PORT=3002
      - COUNTER_URL=http://counter:3003
    ports:
      - 80:3002
    depends_on:
      - counter
