services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    build: .
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 3003:3003
    depends_on:
      - storage
